# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
solc_version = '0.8.30'
evm_version = 'prague'
optimizer_runs = 10_000
ffi = true
ast = true
build_info = true
src = 'src'
out = 'out'
extra_output = ['storageLayout']
libs = ['lib', 'node_modules']
gas_reports = ['*']
fs_permissions = [
    { access = 'read-write', path = '.forge-snapshots/' },
    { access = 'read-write', path = './out/' },
    { access = 'read-write', path = './broadcast' },
    { access = 'read-write', path = './reports' }
]

[lint]
exclude_lints = ['mixed-case-function', 'screaming-snake-case-const']

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[fmt]
line_length = 120
tab_width = 4
indent_style = 'tab'
bracket_spacing = true
int_types = 'preserve'
quote_style = 'single'
sort_imports = true
contract_new_lines = true
multiline_func_header = 'params_first'
single_line_statement_blocks = 'preserve'
number_underscore = 'thousands'
override_spacing = false

[profile.test]
via_ir = true
out = 'out-via-ir'

[fuzz]
runs = 10_000
max_test_rejects = 100_000
dictionary_weight = 60
include_storage = true

[invariant]
runs = 1_000
depth = 500
timeout = 300
dictionary_weight = 80
max_assume_rejects = 65_536
show_edge_coverage = true
show_metrics = true
show_solidity = true

remappings = [
    'forge-std/=lib/forge-std/src',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts'
]

[rpc_endpoints]
sepolia = '${SEPOLIA_RPC}'
ethereum = '${ETHEREUM_RPC}'
amoy = '${AMOY_RPC}'
polygon = '${POLYGON_RPC}'

[etherscan]
sepolia = { key = '${ETHERSCAN_API_KEY}' }
ethereum = { key = '${ETHERSCAN_API_KEY}' }
amoy = { key = '${POLYGONSCAN_API_KEY}' }
polygon = { key = '${POLYGONSCAN_API_KEY}' }
