# .github/workflows/slither.yml
name: Slither (Foundry)
on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Slither
        id: slither
        uses: crytic/slither-action@v0.4.1
        with:
          target: .
          slither-config: slither.config.json   
          fail-on: medium                       
          sarif: results.sarif                  
          slither-args: --json slither-report.json

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

      - name: Upload JSON report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json
