name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show version
        run: forge --version

      - name: Run fmt
        run: forge fmt --check
        id: fmt

      - name: Run build
        run: forge build --sizes
        id: build

      - name: Run tests
        run: forge test -vvv
        id: test
